### ISSUE TITLE
Audio can only be output via HDMI

### ISSUE THREAD

**Issue by xx-li** [Dir3Rav3n/MSI-MAG-Z490-TOMAHAWK-i7-10700-OpenCore-#1]
Thank you for all open source projects. The only difference from you is that the graphics card is the RX5600XT. Other functions work normally, but the audio can only be output through HDMI. The audio output ports on the front and rear panels cannot be used normally. What should I do? Please help me, thanks

![截屏2020-11-28 下午8 49 52](https://user-images.githubusercontent.com/5794847/100515973-53d44e00-31bb-11eb-9d5c-12d7c6c8230e.png)

**Comment by salvadorbrahli** [comment]
Hi. I also use this repo as a reference and my audio didn't work either.
The solution was to use audio layout 11 in my config.plist. You might need a different one. Just follow the official guide for OpenCore [here](https://dortania.github.io/OpenCore-Post-Install/universal/audio.html).

**Comment by Dir3Rav3n** [comment]
Correct, layout might be different. 
Not always one specific layout that works for me would work for another person. 
Please test with different layouts.

**Comment by xx-li** [comment]
I found the layout id supported by my sound card
![截屏2020-11-28 下午11 04 00](https://user-images.githubusercontent.com/5794847/100518713-30ff6500-31ce-11eb-94a2-f6542592c56d.png)
I test all layout id.

when layout id is 1/2/11，my sound output list is as shown.
![截屏2020-11-28 下午10 26 29](https://user-images.githubusercontent.com/5794847/100518752-89366700-31ce-11eb-9701-f10b3691d6b3.png)

when layout id is 29，my sound output list is as shown.
![截屏2020-11-28 下午10 47 45](https://user-images.githubusercontent.com/5794847/100518766-9eab9100-31ce-11eb-97d0-f7b03c8d24e8.png)

But except for HDMI, all audio output interfaces have no sound output.

**Comment by xx-li** [comment]
There is a problem with restarting, everything is ok after shutdown。
