### ISSUE TITLE
[Question] SSDT shoudn't be SSDT-EC-USBX and not SSDT-EC?

### ISSUE THREAD

**Issue by eliasjnior** [Dir3Rav3n/MSI-MAG-Z490-TOMAHAWK-i7-10700-OpenCore-#2]
Hey! I'm just finishing my hackintosh setup and I'm looking to buy this motherboard.

Looking your EFI, I noticed that you included SSDT-EC and not SSDT-EC-USBX as OpenCore guide says [here](https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#desktop).

Did you renamed it or you really included the "wrongly"?

Nice job, by the way. It will help me build my EFI, I have only i5-10600K and RX 5600 XT different from yours.

**Comment by Dir3Rav3n** [comment]
Hi, I just renamed it SSDT-EC just for convenience.
