### ISSUE TITLE
usbport 

### ISSUE THREAD

**Issue by arnolix** [Dir3Rav3n/MSI-MAG-Z490-TOMAHAWK-i7-10700-OpenCore-#3]
Hi, If I use usbport,   My mouse can not moved.      MSI z490 Tomahawk + I7 10700k + RX5700 + Fenvi 1200

**Comment by Dir3Rav3n** [comment]
Which USB port you plugged in the mouse? 
The top 2 usb of the MB are disabled due to USB port map being.

**Comment by arnolix** [comment]
thx, My mouse change to use3.0  It is ok
