### ISSUE TITLE
Front panel microphone input is invalid

### ISSUE THREAD

**Issue by xx-li** [Dir3Rav3n/MSI-MAG-Z490-TOMAHAWK-i7-10700-OpenCore-#4]
After I changed the layoutid to 7, the audio output is normal, but the microphone input interface cannot be used.

**Comment by Dir3Rav3n** [comment]
Hi, you might need to check different layout id, i do not have a front panel audio out or mic input. 
On the back all audio in and out is working correctly for me. you might need to play around with different audio ids.
